@startuml
:Agente:
usecase UC1 as "Enviar Solicitud crédito"
Agente --> UC1
usecase UC2 as "Enviar Solicitud crédito personal"
UC2 -|> UC1
usecase UC3 as "Enviar Solicitud crédito empresarial"
UC3 -|> UC1

@enduml